//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.27 at 05:50:24 PM CEST 
//


package eu.esdihumboldt.hale.server.war.wps;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.opengis.wps._1_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.opengis.wps._1_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InputReferenceType }
     * 
     */
    public InputReferenceType createInputReferenceType() {
        return new InputReferenceType();
    }

    /**
     * Create an instance of {@link Execute }
     * 
     */
    public Execute createExecute() {
        return new Execute();
    }

    /**
     * Create an instance of {@link RequestBaseType }
     * 
     */
    public RequestBaseType createRequestBaseType() {
        return new RequestBaseType();
    }

    /**
     * Create an instance of {@link DataInputsType }
     * 
     */
    public DataInputsType createDataInputsType() {
        return new DataInputsType();
    }

    /**
     * Create an instance of {@link ResponseFormType }
     * 
     */
    public ResponseFormType createResponseFormType() {
        return new ResponseFormType();
    }

    /**
     * Create an instance of {@link LiteralDataType }
     * 
     */
    public LiteralDataType createLiteralDataType() {
        return new LiteralDataType();
    }

    /**
     * Create an instance of {@link ResponseDocumentType }
     * 
     */
    public ResponseDocumentType createResponseDocumentType() {
        return new ResponseDocumentType();
    }

    /**
     * Create an instance of {@link ComplexDataType }
     * 
     */
    public ComplexDataType createComplexDataType() {
        return new ComplexDataType();
    }

    /**
     * Create an instance of {@link DataType }
     * 
     */
    public DataType createDataType() {
        return new DataType();
    }

    /**
     * Create an instance of {@link InputType }
     * 
     */
    public InputType createInputType() {
        return new InputType();
    }

    /**
     * Create an instance of {@link DocumentOutputDefinitionType }
     * 
     */
    public DocumentOutputDefinitionType createDocumentOutputDefinitionType() {
        return new DocumentOutputDefinitionType();
    }

    /**
     * Create an instance of {@link OutputDefinitionType }
     * 
     */
    public OutputDefinitionType createOutputDefinitionType() {
        return new OutputDefinitionType();
    }

    /**
     * Create an instance of {@link InputReferenceType.Header }
     * 
     */
    public InputReferenceType.Header createInputReferenceTypeHeader() {
        return new InputReferenceType.Header();
    }

    /**
     * Create an instance of {@link InputReferenceType.BodyReference }
     * 
     */
    public InputReferenceType.BodyReference createInputReferenceTypeBodyReference() {
        return new InputReferenceType.BodyReference();
    }

}
