//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.12 at 01:46:23 PM CEST 
//


package eu.esdihumboldt.hale.server.war.wps;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Description of the status of process execution. 
 * 
 * <p>Java class for StatusType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StatusType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="ProcessAccepted" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessStarted" type="{http://www.opengis.net/wps/1.0.0}ProcessStartedType"/>
 *         &lt;element name="ProcessPaused" type="{http://www.opengis.net/wps/1.0.0}ProcessStartedType"/>
 *         &lt;element name="ProcessSucceeded" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProcessFailed" type="{http://www.opengis.net/wps/1.0.0}ProcessFailedType"/>
 *       &lt;/choice>
 *       &lt;attribute name="creationTime" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatusType", propOrder = {
    "processAccepted",
    "processStarted",
    "processPaused",
    "processSucceeded",
    "processFailed"
})
public class StatusType {

    @XmlElement(name = "ProcessAccepted")
    protected String processAccepted;
    @XmlElement(name = "ProcessStarted")
    protected ProcessStartedType processStarted;
    @XmlElement(name = "ProcessPaused")
    protected ProcessStartedType processPaused;
    @XmlElement(name = "ProcessSucceeded")
    protected String processSucceeded;
    @XmlElement(name = "ProcessFailed")
    protected ProcessFailedType processFailed;
    @XmlAttribute(name = "creationTime", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;

    /**
     * Gets the value of the processAccepted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessAccepted() {
        return processAccepted;
    }

    /**
     * Sets the value of the processAccepted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessAccepted(String value) {
        this.processAccepted = value;
    }

    /**
     * Gets the value of the processStarted property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessStartedType }
     *     
     */
    public ProcessStartedType getProcessStarted() {
        return processStarted;
    }

    /**
     * Sets the value of the processStarted property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessStartedType }
     *     
     */
    public void setProcessStarted(ProcessStartedType value) {
        this.processStarted = value;
    }

    /**
     * Gets the value of the processPaused property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessStartedType }
     *     
     */
    public ProcessStartedType getProcessPaused() {
        return processPaused;
    }

    /**
     * Sets the value of the processPaused property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessStartedType }
     *     
     */
    public void setProcessPaused(ProcessStartedType value) {
        this.processPaused = value;
    }

    /**
     * Gets the value of the processSucceeded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessSucceeded() {
        return processSucceeded;
    }

    /**
     * Sets the value of the processSucceeded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessSucceeded(String value) {
        this.processSucceeded = value;
    }

    /**
     * Gets the value of the processFailed property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessFailedType }
     *     
     */
    public ProcessFailedType getProcessFailed() {
        return processFailed;
    }

    /**
     * Sets the value of the processFailed property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessFailedType }
     *     
     */
    public void setProcessFailed(ProcessFailedType value) {
        this.processFailed = value;
    }

    /**
     * Gets the value of the creationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationTime() {
        return creationTime;
    }

    /**
     * Sets the value of the creationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationTime(XMLGregorianCalendar value) {
        this.creationTime = value;
    }

}
