<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    exclude-result-prefixes="f xmi xsd data"
    xmlns:xmi="http://schema.omg.org/spec/XMI/2.1"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		xmlns:gml="http://www.opengis.net/gml/3.2"
		xmlns:f="gmlas-toolkit:functions"
		xmlns:data="gmlas-toolkit:data"
>

  <!-- = predefined type functions ======================================================== -->

  <xsl:key name="type-by-uml-type" match="//data:type" use="data:uml-type" />

  <xsl:function name="f:uml-type.is-predefinied-type" as="xsd:boolean">
    <xsl:param name="type-name" as="xsd:string" />
    <xsl:value-of select="count(document('')/key('type-by-uml-type', $type-name))!=0"/>
  </xsl:function>

  <xsl:function name="f:uml-type.get-element-name" as="xsd:string">
    <xsl:param name="type-name" as="xsd:string" />
    <xsl:value-of select="document('')/key('type-by-uml-type', $type-name)/data:gml-element"/>
  </xsl:function>

  <xsl:function name="f:uml-type.get-type-name" as="xsd:string">
    <xsl:param name="type-name" as="xsd:string" />
    <xsl:value-of select="document('')/key('type-by-uml-type', $type-name)/data:gml-type"/>
  </xsl:function>

  <xsl:function name="f:uml-type.get-property-type-name" as="xsd:string">
    <xsl:param name="type-name" as="xsd:string" />
    <xsl:value-of select="document('')/key('type-by-uml-type', $type-name)/data:gml-property-type[1]"/>
  </xsl:function>

  <data:type-map>
    <data:type>
      <data:uml-type>GM_Object</data:uml-type>
      <data:gml-element>gml:AbstractGeometry</data:gml-element>
      <data:gml-type>gml:AbstractGeometryType</data:gml-type>
      <data:gml-property-type>gml:GeometryPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Primitive</data:uml-type>
      <data:gml-element>gml:AbstractGeometricPrimtive</data:gml-element>
      <data:gml-type>gml:AbstractGeometricPrimtiveType</data:gml-type>
      <data:gml-property-type>gml:GeometricPrimtivePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>DirectPosition</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:DirectPositionType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Position</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type isGroup="true">gml:geometricPositionGroup</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_PointArray</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type isGroup="true">gml:geometricPositionListGroup</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Point</data:uml-type>
      <data:gml-element>gml:Point</data:gml-element>
      <data:gml-type>gml:PointType</data:gml-type>
      <data:gml-property-type>gml:PointPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Curve</data:uml-type>
      <data:gml-element>gml:Curve</data:gml-element>
      <data:gml-type>gml:CurveType</data:gml-type>
      <data:gml-property-type>gml:CurvePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Surface</data:uml-type>
      <data:gml-element>gml:Surface</data:gml-element>
      <data:gml-type>gml:SurfaceType</data:gml-type>
      <data:gml-property-type>gml:SurfacePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_PolyhedralSurface</data:uml-type>
      <data:gml-element>gml:PolyhedralSurface</data:gml-element>
      <data:gml-type>gml:PolyhedralSurfaceType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_TriangulatedSurface</data:uml-type>
      <data:gml-element>gml:TriangulatedSurface</data:gml-element>
      <data:gml-type>gml:TriangulatedSurfaceType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Tin</data:uml-type>
      <data:gml-element>gml:Tin</data:gml-element>
      <data:gml-type>gml:TinType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Solid</data:uml-type>
      <data:gml-element>gml:Solid</data:gml-element>
      <data:gml-type>gml:SolidType</data:gml-type>
      <data:gml-property-type>gml:SolidPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_OrientableCurve</data:uml-type>
      <data:gml-element>gml:OrientableCurve</data:gml-element>
      <data:gml-type>gml:OrientableCurveType</data:gml-type>
      <data:gml-property-type>gml:CurvePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_OrientableSurface</data:uml-type>
      <data:gml-element>gml:OrientableSurface</data:gml-element>
      <data:gml-type>gml:OrientableSurfaceType</data:gml-type>
      <data:gml-property-type>gml:SurfacePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Ring</data:uml-type>
      <data:gml-element>gml:Ring</data:gml-element>
      <data:gml-type>gml:RingType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Shell</data:uml-type>
      <data:gml-element>gml:Shell</data:gml-element>
      <data:gml-type>gml:ShellType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:LineString</data:gml-element>
      <data:gml-type>gml:LineStringType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:Polygon</data:gml-element>
      <data:gml-type>gml:PolygonType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:LinearRing</data:gml-element>
      <data:gml-type>gml:LinearRingType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_CompositePoint</data:uml-type>
      <data:gml-element>gml:Point</data:gml-element>
      <data:gml-type>gml:PointType</data:gml-type>
      <data:gml-property-type>gml:PointPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_CompositeCurve</data:uml-type>
      <data:gml-element>gml:CompositeCurve</data:gml-element>
      <data:gml-type>gml:CompositeCurveType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_CompositeSurface</data:uml-type>
      <data:gml-element>gml:CompositeSurface</data:gml-element>
      <data:gml-type>gml:CompositeSurfaceType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_CompositeSolid</data:uml-type>
      <data:gml-element>gml:CompositeSolid</data:gml-element>
      <data:gml-type>gml:CompositeSolidType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Complex</data:uml-type>
      <data:gml-element>gml:GeometricComplex</data:gml-element>
      <data:gml-type>gml:GeometricComplexType</data:gml-type>
      <data:gml-property-type>gml:GeometricComplexPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Aggregate</data:uml-type>
      <data:gml-element>gml:MultiGeometry</data:gml-element>
      <data:gml-type>gml:MultiGeometryType</data:gml-type>
      <data:gml-property-type>gml:MultiGeometryPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_MultiPoint</data:uml-type>
      <data:gml-element>gml:MultiPoint</data:gml-element>
      <data:gml-type>gml:MultiPointType</data:gml-type>
      <data:gml-property-type>gml:MultiPointPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_MultiCurve</data:uml-type>
      <data:gml-element>gml:MultiCurve</data:gml-element>
      <data:gml-type>gml:MultiCurveType</data:gml-type>
      <data:gml-property-type>gml:MultiCurvePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_MultiSurface</data:uml-type>
      <data:gml-element>gml:MultiSurface</data:gml-element>
      <data:gml-type>gml:MultiSurfaceType</data:gml-type>
      <data:gml-property-type>gml:MultiSurfacePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_MultiSolid</data:uml-type>
      <data:gml-element>gml:MultiSolid</data:gml-element>
      <data:gml-type>gml:MultiSolidType</data:gml-type>
      <data:gml-property-type>gml:MultiSolidPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_MultiPrimitive</data:uml-type>
      <data:gml-element>gml:MultiGeometry</data:gml-element>
      <data:gml-type>gml:MultiGeometryType</data:gml-type>
      <data:gml-property-type>gml:MultiGeometryPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_CurveSegment</data:uml-type>
      <data:gml-element>gml:AbstractCurveSegment</data:gml-element>
      <data:gml-type>gml:AbstractCurveSegmentType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Arc</data:uml-type>
      <data:gml-element>gml:Arc</data:gml-element>
      <data:gml-type>gml:ArcType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_ArcByBulge</data:uml-type>
      <data:gml-element>gml:ArcByBulge</data:gml-element>
      <data:gml-type>gml:ArcByBulgeType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:ArcByCenterPoint</data:gml-element>
      <data:gml-type>gml:ArcByCenterPointType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_ArcString</data:uml-type>
      <data:gml-element>gml:ArcString</data:gml-element>
      <data:gml-type>gml:ArcStringType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_ArcStringByBulge</data:uml-type>
      <data:gml-element>gml:ArcStringByBulge</data:gml-element>
      <data:gml-type>gml:ArcStringByBulgeType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Bezier</data:uml-type>
      <data:gml-element>gml:Bezier</data:gml-element>
      <data:gml-type>gml:BezierType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_BsplineCurve</data:uml-type>
      <data:gml-element>gml:BSpline</data:gml-element>
      <data:gml-type>gml:BSplineType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Circle</data:uml-type>
      <data:gml-element>gml:Circle</data:gml-element>
      <data:gml-type>gml:CircleType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:CircleByCenterPoint</data:gml-element>
      <data:gml-type>gml:CircleByCenterPointType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Clothoid</data:uml-type>
      <data:gml-element>gml:Clothoid</data:gml-element>
      <data:gml-type>gml:ClothoidType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_CubicSpline</data:uml-type>
      <data:gml-element>gml:CubicSpline</data:gml-element>
      <data:gml-type>gml:CubicSplineType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_GeodesicString</data:uml-type>
      <data:gml-element>gml:GeodesicString</data:gml-element>
      <data:gml-type>gml:GeodesicStringType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_LineString</data:uml-type>
      <data:gml-element>gml:LineStringSegment</data:gml-element>
      <data:gml-type>gml:LineStringSegmentType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_OffsetCurve</data:uml-type>
      <data:gml-element>gml:OffsetCurve</data:gml-element>
      <data:gml-type>gml:OffsetCurveType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_SurfacePatch</data:uml-type>
      <data:gml-element>gml:AbstractSurfacePatch</data:gml-element>
      <data:gml-type>gml:AbstractSurfacePatchType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_GriddedSurface</data:uml-type>
      <data:gml-element>gml:AbstractGriddedSurface</data:gml-element>
      <data:gml-type>gml:AbstractGriddedSurfaceType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_ParametricCurveSurface</data:uml-type>
      <data:gml-element>gml:AbstractParametricCurveSurface</data:gml-element>
      <data:gml-type>gml:AbstractParametricCurveSurfaceType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Cone</data:uml-type>
      <data:gml-element>gml:Cone</data:gml-element>
      <data:gml-type>gml:ConeType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Cylinder</data:uml-type>
      <data:gml-element>gml:Cylinder</data:gml-element>
      <data:gml-type>gml:CylinderType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Geodesic</data:uml-type>
      <data:gml-element>gml:Geodesic</data:gml-element>
      <data:gml-type>gml:GeodesicType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Polygon</data:uml-type>
      <data:gml-element>gml:PolygonPatch</data:gml-element>
      <data:gml-type>gml:PolygonPatchType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:Rectangle</data:gml-element>
      <data:gml-type>gml:RectangleType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Sphere</data:uml-type>
      <data:gml-element>gml:Sphere</data:gml-element>
      <data:gml-type>gml:SphereType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GM_Triangle</data:uml-type>
      <data:gml-element>gml:Triangle</data:gml-element>
      <data:gml-type>gml:TriangleType</data:gml-type>
      <data:gml-property-type></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_Object</data:uml-type>
      <data:gml-element>gml:AbstractTopology</data:gml-element>
      <data:gml-type>gml:AbstractTopologyType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_Node</data:uml-type>
      <data:gml-element>gml:Node</data:gml-element>
      <data:gml-type>gml:NodeType</data:gml-type>
      <data:gml-property-type>gml:DirectedNodePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_Edge</data:uml-type>
      <data:gml-element>gml:Edge</data:gml-element>
      <data:gml-type>gml:EdgeType</data:gml-type>
      <data:gml-property-type>gml:DirectedEdgePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_Face</data:uml-type>
      <data:gml-element>gml:Face</data:gml-element>
      <data:gml-type>gml:FaceType</data:gml-type>
      <data:gml-property-type>gml:DirectedFacePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_Solid</data:uml-type>
      <data:gml-element>gml:TopoSolid</data:gml-element>
      <data:gml-type>gml:TopoSolidType</data:gml-type>
      <data:gml-property-type>gml:DirectedTopoSolidPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_DirectedNode</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:DirectedNodePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_DirectedEdge</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:DirectedEdgePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_DirectedFace</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:DirectedFacePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_DirectedSolid</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:DirectedTopoSolidPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TP_Complex</data:uml-type>
      <data:gml-element>gml:TopoComplex</data:gml-element>
      <data:gml-type>gml:TopoComplexType</data:gml-type>
      <data:gml-property-type>gml:TopoComplexPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:TopoPoint</data:gml-element>
      <data:gml-type>gml:TopoPointType</data:gml-type>
      <data:gml-property-type>gml:TopoPointPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:TopoCurve</data:gml-element>
      <data:gml-type>gml:TopoCurveType</data:gml-type>
      <data:gml-property-type>gml:TopoCurvePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:TopoSurface</data:gml-element>
      <data:gml-type>gml:TopoSurfaceType</data:gml-type>
      <data:gml-property-type>gml:TopoSurfacePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type></data:uml-type>
      <data:gml-element>gml:TopoVolume</data:gml-element>
      <data:gml-type>gml:TopoVolumeType</data:gml-type>
      <data:gml-property-type>gml:TopoVolumePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Object</data:uml-type>
      <data:gml-element>gml:AbstractTimeObject</data:gml-element>
      <data:gml-type>gml:AbstractTimeObjectType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Complex</data:uml-type>
      <data:gml-element>gml:AbstractTimeComplex</data:gml-element>
      <data:gml-type>gml:AbstractTimeComplexType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_GeometricPrimitive</data:uml-type>
      <data:gml-element>gml:AbstractTimeGeometricPrimtive</data:gml-element>
      <data:gml-type>gml:AbstractTimeGeometricPrimtiveType</data:gml-type>
      <data:gml-property-type>gml:TimeGeometricPrimtivePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Instant</data:uml-type>
      <data:gml-element>gml:TimeInstant</data:gml-element>
      <data:gml-type>gml:TimeInstantType</data:gml-type>
      <data:gml-property-type>gml:TimeInstantPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Period</data:uml-type>
      <data:gml-element>gml:TimePeriod</data:gml-element>
      <data:gml-type>gml:TimePeriodType</data:gml-type>
      <data:gml-property-type>gml:TimePeriodPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_TopologicalComplex</data:uml-type>
      <data:gml-element>gml:TimeTopologyComplex</data:gml-element>
      <data:gml-type>gml:TimeTopologyComplexType</data:gml-type>
      <data:gml-property-type>gml:TimeTopologyComplexPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_TopologicalPrimitive</data:uml-type>
      <data:gml-element>gml:AbstractTimeTopologyPrimtive</data:gml-element>
      <data:gml-type>gml:AbstractTimeTopologyPrimtiveType</data:gml-type>
      <data:gml-property-type>gml:TimeTopologyPrimtivePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Node</data:uml-type>
      <data:gml-element>gml:TimeNode</data:gml-element>
      <data:gml-type>gml:TimeNodeType</data:gml-type>
      <data:gml-property-type>gml:TimeNodePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Edge</data:uml-type>
      <data:gml-element>gml:TimeEdge</data:gml-element>
      <data:gml-type>gml:TimeEdgeType</data:gml-type>
      <data:gml-property-type>gml:TimeEdgePropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_PeriodDuration</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:duration (property element), xsd:duration</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_IntervalLength</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type isGroup="true">gml:timeInterval</data:gml-property-type>
      <data:gml-property-type>gml:TimeIntervalLengthType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Duration</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type isGroup="true">gml:timeLength</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Position</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:TimePositionType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_IndeterminateValue</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>@TimeIndeterminateValue</data:gml-property-type>
      <!--(attribute on TimePositionType)-->
    </data:type>
    <data:type>
      <data:uml-type>TM_Coordinate</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:decimal</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_CalDate</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:CalDate</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_ClockTime</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:time</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_DateAndTime</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:dateTime</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Calendar</data:uml-type>
      <data:gml-element>gml:TimeCalendar</data:gml-element>
      <data:gml-type>gml:TimeCalendarType</data:gml-type>
      <data:gml-property-type>gml:TimeCalendarPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_CalendarEra</data:uml-type>
      <data:gml-element>gml:TimeCalendarEra</data:gml-element>
      <data:gml-type>gml:TimeCalendarEraType</data:gml-type>
      <data:gml-property-type>gml:TimeCalendarEraPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_Clock</data:uml-type>
      <data:gml-element>gml:TimeClock</data:gml-element>
      <data:gml-type>gml:TimeClockType</data:gml-type>
      <data:gml-property-type>gml:TimeClockPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_CoordinateSystem</data:uml-type>
      <data:gml-element>gml:TimeCoordinateSystem</data:gml-element>
      <data:gml-type>gml:TimeCoordinateSystemType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_OrdinalReferenceSystem</data:uml-type>
      <data:gml-element>gml:TimeOrdinalReferenceSystem</data:gml-element>
      <data:gml-type>gml:TimeOrdinalReferenceSystemType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>TM_OrdinalEra</data:uml-type>
      <data:gml-element>gml:TimeOrdinalEra</data:gml-element>
      <data:gml-type>gml:TimeOrdinalEraType</data:gml-type>
      <data:gml-property-type>gml:TimeOrdinalEraPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>SC_CRS</data:uml-type>
      <data:gml-element>gml:AbstractCRS</data:gml-element>
      <data:gml-type>gml:AbstractCRSType</data:gml-type>
      <data:gml-property-type>gml:CRSPropertyType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>SI_LocationInstance</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:LocationName</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_Coverage</data:uml-type>
      <data:gml-element>gml:AbstractCoverage</data:gml-element>
      <data:gml-type>gml:AbstractCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_ContinuousCoverage</data:uml-type>
      <data:gml-element>gml:AbstractContinuousCoverage</data:gml-element>
      <data:gml-type>gml:AbstractContinuousCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_DiscreteCoverage</data:uml-type>
      <data:gml-element>gml:AbstractDiscreteCoverage</data:gml-element>
      <data:gml-type>gml:DiscreteCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_DiscretePointCoverage</data:uml-type>
      <data:gml-element>gml:MultiPointCoverage</data:gml-element>
      <data:gml-type>gml:MultiPointCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_DiscreteCurveCoverage</data:uml-type>
      <data:gml-element>gml:MultiCurveCoverage</data:gml-element>
      <data:gml-type>gml:MultiCurveCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_DiscreteSurfaceCoverage</data:uml-type>
      <data:gml-element>gml:MultiSurfaceCoverage</data:gml-element>
      <data:gml-type>gml:MultiSurfaceCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_DiscreteSolidCoverage</data:uml-type>
      <data:gml-element>gml:MultiSolidCoverage</data:gml-element>
      <data:gml-type>gml:MultiSolidCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CV_DiscreteGridPointCoverage</data:uml-type>
      <data:gml-element>gml:GridCoverage</data:gml-element>
      <data:gml-type>gml:GridCoverageType</data:gml-type>
      <data:gml-property-type isAnonymous="true"></data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>CharacterString</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:string</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Boolean</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:boolean</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Real, Number</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:double</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Decimal</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:decimal</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Date</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:date</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Time</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:time</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>DateTime</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:dateTime</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Integer</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>xsd:integer</data:gml-property-type>
      <data:gml-property-type>xsd:nonPositiveInteger</data:gml-property-type>
      <data:gml-property-type>xsd:negativeInteger</data:gml-property-type>
      <data:gml-property-type>xsd:nonNegativeInteger</data:gml-property-type>
      <data:gml-property-type>xsd:positiveInteger</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Vector</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:VectorType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>GenericName</data:uml-type>
      <data:uml-type>LocalName</data:uml-type>
      <data:uml-type>ScopeName</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:CodeType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Length</data:uml-type>
      <data:uml-type>Distance</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:LengthType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Angle</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:AngleType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Speed</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:SpeedType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Scale</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:ScaleType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Area</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:AreaType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Volume</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:VolumeType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Measure</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:MeasureType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>Sign</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:SignType</data:gml-property-type>
    </data:type>
    <data:type>
      <data:uml-type>UnitOfMeasure</data:uml-type>
      <data:gml-element></data:gml-element>
      <data:gml-type></data:gml-type>
      <data:gml-property-type>gml:UnitOfMeasureType</data:gml-property-type>
    </data:type>
  </data:type-map>

</xsl:stylesheet>
