/*
 * Copyright (c) 2018 wetransform GmbH
 * 
 * All rights reserved. This program and the accompanying materials are made
 * available under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 * 
 * You should have received a copy of the GNU Lesser General Public License
 * along with this distribution. If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors:
 *     wetransform GmbH <http://www.wetransform.to>
 */

package eu.esdihumboldt.hale.io.deegree.mapping.config;

/**
 * Predefined modes for generating an ID prefix.
 * 
 * @author Simon Templer
 */
public enum IDPrefixMode {

	/** Default configuration by deegree */
	deegree("Default prefix generated by deegree"),

	/** Use only the element name as-is and w/o namespace */
	element("Use the feature type (XML element) name plus an underscore");

	// TODO also a mode that allows using a custom script?

	private final String description;

	IDPrefixMode(String description) {
		this.description = description;
	}

	@SuppressWarnings("javadoc")
	public String getDescription() {
		return description;
	}

}
