//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.07 at 01:07:31 PM CET 
//

package eu.esdihumboldt.commons.mediator.transformer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ComplexDataInput complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ComplexDataInput">
 *   &lt;complexContent>
 *     &lt;extension base="{}DataInput">
 *       &lt;sequence>
 *         &lt;element name="featureName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="groundingURI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="filterEncoding" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComplexDataInput", propOrder = { "featureName",
		"groundingURI", "filterEncoding" })
public class ComplexDataInput extends DataInput {

	@XmlElement(required = true)
	protected String featureName;
	@XmlElement(required = true)
	protected String groundingURI;
	@XmlElement(required = true)
	protected String filterEncoding;

	/**
	 * Gets the value of the featureName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFeatureName() {
		return featureName;
	}

	/**
	 * Sets the value of the featureName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFeatureName(String value) {
		this.featureName = value;
	}

	/**
	 * Gets the value of the groundingURI property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGroundingURI() {
		return groundingURI;
	}

	/**
	 * Sets the value of the groundingURI property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGroundingURI(String value) {
		this.groundingURI = value;
	}

	/**
	 * Gets the value of the filterEncoding property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFilterEncoding() {
		return filterEncoding;
	}

	/**
	 * Sets the value of the filterEncoding property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFilterEncoding(String value) {
		this.filterEncoding = value;
	}

}
