//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.01.07 at 01:07:31 PM CET 
//
package eu.esdihumboldt.commons.mediator.transformer;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for TransformerDataInput complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="TransformerDataInput">
 *   &lt;complexContent>
 *     &lt;extension base="{}DataInput">
 *       &lt;sequence>
 *         &lt;element name="previousTransformerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransformerDataInput", propOrder = { "previousTransformerID" })
public class TransformerDataInput extends DataInput {

	@XmlElement(required = true)
	protected String previousTransformerID;

	/**
	 * Gets the value of the previousTransformerID property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getPreviousTransformerID() {
		return previousTransformerID;
	}

	/**
	 * Sets the value of the previousTransformerID property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setPreviousTransformerID(String value) {
		this.previousTransformerID = value;
	}
}
