//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.16 at 12:50:12 PM CEST 
//

package eu.esdihumboldt.goml.omwg;


/**
 * TODO: 'oneOf' and 'between' were added by mdv, might have to go elsewhere
 * 
 * <xs:simpleType name="comparatorEnumType">
 */	
public enum ComparatorType {

    EQUAL("equal"),
    NOT_EQUAL("not-equal"),
    LESS_THAN("less-than"),
    LESS_THAN_OR_EQUAL("less-than-or-equal"),
    GREATER_THAN("greater-than"),
    GREATER_THAN_OR_EQUAL("greater-than-or-equal"),
    CONTAINS("contains"),
    STARTS_WITH("starts-with"),
    ENDS_WITH("ends-with"),
    MATCHES("matches"),
    COLLECTION_CONTAINS("collection-contains"),
    INCLUDES("includes"),
    INCLUDES_STRICTLY("includes-strictly"),
    EMPTY("empty"),
    ONE_OF("oneOf"),
    BETWEEN("between");

    private final String value;

    ComparatorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ComparatorType fromValue(String v) {
        for (ComparatorType c: ComparatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        //throw new IllegalArgumentException(v);
        return null;
    }

}
