name: Check labels

on:
  pull_request:
    branches:
      - master  # Trigger only on PRs to master
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  require-challenge:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: mheap/github-action-required-labels@d25134c992b943fb6ad00c25ea00eb5988c0a9dd # v5.4.2
        with:
          mode: minimum
          count: 1
          labels: |
            challenged
            renovate/patch
            renovate/minor
          add_comment: ${{ ! github.event.pull_request.head.repo.fork }}
          message: "This PR cannot be merged yet because a required label is missing: `{{ provided }}`. It needs to be added before this PR can be merged."
