name: Check labels

on:
  pull_request:
    branches:
      - master  # Trigger only on PRs to master
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  require-challenge:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: mheap/github-action-required-labels@388fd6af37b34cdfe5a23b37060e763217e58b03 # 5.5.0
        with:
          mode: minimum
          count: 1
          labels: |
            challenged
            renovate/patch
            renovate/minor
          add_comment: ${{ ! github.event.pull_request.head.repo.fork }}
          message: "This PR cannot be merged yet because a required label is missing: `{{ provided }}`. It needs to be added before this PR can be merged."
