name: Publish Products

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        description: "Release version without v prefix, e.g. 6.1.2"
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_PASSWORD:
        required: true
      BUILD_ARCHIVE_ACCESS_KEY:
        required: true
      BUILD_ARCHIVE_SECRET_KEY:
        required: true
      SLACK_NOTIFICATIONS_BOT_TOKEN:
        required: true

jobs:
  publish-products:
    name: Publish products and update site
    runs-on: ubuntu-latest
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.6
          checkout-ref: refs/tags/v${{ inputs.version }} # check out release tag

      - name: Install genisoimage # required for Mac build
        run: sudo apt-get install -y genisoimage

      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Install AWS CLI # Required for uploading update site
        uses: unfor19/install-aws-cli-action@f5b46b7f32cf5e7ebd652656c5036bf83dd1e60c # 1.0.8
        with:
          version: 1

      - name: Clean
        run: ./build.sh clean
        working-directory: ./build

      - name: Build products
        run: |
          ./build.sh product --arch x86_64 --os linux HALE
          ./build.sh product --arch x86_64 --os windows HALE
          ./build.sh product --arch x86_64 --os macosx HALE
          ./build.sh product --arch x86_64 --os linux --publish Infocenter
        working-directory: ./build

        # use GitHub CLI to upload asset to release
        # see https://cli.github.com/manual/gh_release_upload
      - name: Add HALE products to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo "Adding to release assets..."
          gh release upload v${{ inputs.version }} build/target/*.tar.gz --repo ${{ github.repository }} --clobber
          gh release upload v${{ inputs.version }} build/target/*.zip --repo ${{ github.repository }} --clobber
          gh release upload v${{ inputs.version }} build/target/*.dmg --repo ${{ github.repository }} --clobber
        shell: bash

      - name: Upload update site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.BUILD_ARCHIVE_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.BUILD_ARCHIVE_SECRET_KEY }}
        run: ./upload-site.sh
        working-directory: ./build

        # https://github.com/marketplace/actions/slack-notify-build
      - name: Notify failure to Slack
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@3665186a8c1a022b28a1dbe0954e73aa9081ea9e # v1.6.0
        with:
          channel: build-failures
          status: FAILED
          color: danger
