---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Scan for secrets

on:
  push:
    branches:
      - "**"

jobs:
  scan-for-secrets:
    name: Scan for secrets
    uses: wetransform/gha-workflows/.github/workflows/scan-for-secrets.yml@6cf8743e1cdaff405473951cc6ad4eadaf2226cc # v4.1.2
    secrets:
      SLACK_EXPOSED_SECRETS_WEBHOOK: ${{ secrets.SLACK_EXPOSED_SECRETS_WEBHOOK }}
