---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Scan for secrets

on:
  push:
    branches:
      - "**"

jobs:
  scan-for-secrets:
    name: Scan for secrets
    uses: wetransform/gha-workflows/.github/workflows/scan-for-secrets.yml@efabecf2fba436e990a9f9865ed4532845e1e710 # v4.6.1
    secrets:
      SLACK_EXPOSED_SECRETS_WEBHOOK: ${{ secrets.SLACK_EXPOSED_SECRETS_WEBHOOK }}
