---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Scan for secrets

on:
  push:
    branches:
      - "**"

jobs:
  scan-for-secrets:
    name: Scan for secrets
    uses: wetransform/gha-workflows/.github/workflows/scan-for-secrets.yml@906990fde86426c27eb355b1600afbcda8fddc25 # v4.1.5
    secrets:
      SLACK_EXPOSED_SECRETS_WEBHOOK: ${{ secrets.SLACK_EXPOSED_SECRETS_WEBHOOK }}
