name: Windows installer

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  installer:
    # Only on main repository (don't publish on forks)
    if: github.repository_owner == 'halestudio'

    name: Build Windows installer
    runs-on: windows-latest
    steps:
      - name: Setup Maven
        uses: s4u/setup-maven-action@ba34de01b7f4ba2ab8e2860df8993a29f4477056 # v1.20.0
        with:
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.6

      - name: Build installer
        run: |
          build.bat product -o windows -a x86_64 HALE
        shell: cmd

      - name: Upload hale studio build (Installer)
        id: upload-msi
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: hale studio (Installer)
          path: build/target/*.msi
          retention-days: 90
